services:
  mdp-client:
    container_name: mdp-client
    restart: unless-stopped
    image: nemanjamitic/mern-boilerplate-client:latest
    build:
      context: ./client
      dockerfile: docker/Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=154331370847-dkmkdgprhjenmnhd4d7g33ui2jg5fk9u.apps.googleusercontent.com
    depends_on:
      - mdp-server
    networks:
      - internal-client
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL
      - VITE_GOOGLE_CLIENT_ID=154331370847-dkmkdgprhjenmnhd4d7g33ui2jg5fk9u.apps.googleusercontent.com
    env_file:
      - ./client/.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.mb-client-secure.rule=Host(${SITE_HOSTNAME}) && !(PathPrefix(/api) || PathPrefix(/auth) || PathPrefix(/public/images))'
      - 'traefik.http.routers.mb-client-secure.entrypoints=websecure'
      - 'traefik.http.routers.mb-client-secure.service=mb-client-svc'
      - 'traefik.http.services.mb-client-svc.loadbalancer.server.port=80'
    ports:
      - '3080:80'

  mdp-server:
    container_name: mdp-server
    restart: unless-stopped
    image: nemanjamitic/mern-boilerplate-server:latest
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-mongo
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI_DEV=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mdp-mongo:27017/CITI_Cluster?authSource=admin
      - MONGO_URI_PROD=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mdp-mongo:27017/CITI_Cluster?authSource=admin
      - NODE_ENV=production
      - PORT=80
      - RUN_SEED_ON_STARTUP=true
    volumes:
      - ./server/public/images:/home/node/app/server/public/images
    networks:
      - default
      - internal-client
    ports:
      - '5000:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.mb-server-secure.rule=Host(${SITE_HOSTNAME}) && (PathPrefix(/api) || PathPrefix(/auth) || PathPrefix(/public/images))'
      - 'traefik.http.routers.mb-server-secure.entrypoints=websecure'
      - 'traefik.http.routers.mb-server-secure.service=mb-server-svc'
      - 'traefik.http.services.mb-server-svc.loadbalancer.server.port=80'

  mdp-mongo:
    image: mongo:6.0.3
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    env_file:
      - ./server/.env
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default
  
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./server/.env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mdp-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mdp-mongo
    networks:
      - default
    

networks:
  default:
    name: mdp-default
  internal-client:
    name: mdp-client